### ISSUE TITLE
Second is always either 1 or 2

### ISSUE THREAD

**Issue by ASomerN** [addingwell/formatted-date-variable#1]
Hi,

Great variable, why didn't GTMs have this API!?

When I'm using this, either setting "now" or putting a millisecond timestamp in, the seconds always appear to return either a 1 or a 2. and nothing in milliseconds:

![image](https://github.com/addingwell/formatted-date-variable/assets/29146770/0e302add-d6db-4708-ab82-896a065af9fb)

![image](https://github.com/addingwell/formatted-date-variable/assets/29146770/331ac46c-61e1-4bc2-8780-8b691cd49bb5)

Using the default settings for Format: %YYYY%-%MM%-%DD%T%hh%:%mm%:%ss%.%mmm%Z

**Comment by WFrancois** [comment]
Hey!

Looking at the code, it looks like the explanation is wrong, and %sss% should be used to get milliseconds, instead of %mmm%, I'll update this, thanks for reporting!

For the seconds however, unsure what's happening, as I'm not seeing this on my setup?
What happens if you put as timestamp value `1668087995262` and format `%YYYY%-%MM%-%DD%T%hh%:%mm%:%ss%.%sss%Z`? You should get `2022-11-10T13:46:35.262Z`

**Comment by ASomerN** [comment]
Hi,
That was fast! it fixed the issue thank you.
Really good variable.
Cheers!

**Comment by WFrancois** [comment]
Nice, glad it fixed it for you!
